baseURL = "https://www.unknownsky.net"
languageCode = "en-us"
title = "My Portal"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    userName  = "yukuro"
    pcName = "myPortal"
    workDir = "works"
    profile = "profile.txt"
    scheme = "Dracula"

    terminalDelay = 15

    description = """
    Hi!
    I am Yukuro.
    Intersted in : authentication, 3d printing etc...
    Skill : Java, Python, Hugo, Docker etc...

    """

    [Params.Tree]
    use = true
    folderName = "myActivity"
    files = [
        ["GitHub", "https://github.com/Yukuro"],
        ["X(Formerly Twitter)", "https://x.com/kurokuro_dev"],
        ["My blog", "https://yukuro.hatenablog.com/"],
        ["hugo-theme-shell", "https://github.com/Yukuro/hugo-theme-shell"],
    ]
